/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vodostaj.reka;

import java.io.Console;
import java.util.GregorianCalendar;

/**
 *
 * @author Jana Jovanovic
 */
public class vodostajForm extends javax.swing.JFrame {

    
    private VodostajGUI vodostaj = new VodostajGUI();
    
    public vodostajForm() {
        initComponents();
        
        DanComboBox.removeAllItems();
        for (int i=1; i<=31; i++){
            DanComboBox.addItem(Integer.toString(i));
        }
        
        MesecComboBox.removeAllItems();
        for (int i=1; i<=12; i++){
            MesecComboBox.addItem(Integer.toString(i));
        }
        
        GodinaComboBox.removeAllItems();
        for (int i=2010; i<=2015; i++){
            GodinaComboBox.addItem(Integer.toString(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RezultatTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DanComboBox = new javax.swing.JComboBox<>();
        MesecComboBox = new javax.swing.JComboBox<>();
        GodinaComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VodostajTextPane = new javax.swing.JTextPane();
        UnesiButton = new javax.swing.JButton();
        IzvestajButton = new javax.swing.JButton();
        PrikaziSveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NazivTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vodostaj");

        jLabel1.setText("Naziv");

        RezultatTextArea.setColumns(20);
        RezultatTextArea.setRows(5);
        jScrollPane1.setViewportView(RezultatTextArea);

        jLabel2.setText("Dan");

        jLabel3.setText("Mesec");

        jLabel4.setText("Godina");

        DanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanComboBoxActionPerformed(evt);
            }
        });

        MesecComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesecComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesecComboBoxActionPerformed(evt);
            }
        });

        GodinaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GodinaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GodinaComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Vodostaj");

        jScrollPane3.setViewportView(VodostajTextPane);

        UnesiButton.setText("Unesi");
        UnesiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnesiButtonActionPerformed(evt);
            }
        });

        IzvestajButton.setText("Izvestaj");
        IzvestajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzvestajButtonActionPerformed(evt);
            }
        });

        PrikaziSveButton.setText("Prikazi sve");
        PrikaziSveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrikaziSveButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(NazivTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel3)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MesecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GodinaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(UnesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrikaziSveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IzvestajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GodinaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnesiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrikaziSveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IzvestajButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanComboBoxActionPerformed
        
    }//GEN-LAST:event_DanComboBoxActionPerformed

    private void MesecComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesecComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesecComboBoxActionPerformed

    private void GodinaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GodinaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GodinaComboBoxActionPerformed

    private void UnesiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnesiButtonActionPerformed
        try{
        Reka reka = new Reka();
        reka.setNaziv(NazivTextPane.getText());
        reka.setVodostaj(Double.parseDouble(VodostajTextPane.getText()));
        
        int dan = Integer.parseInt((String) DanComboBox.getSelectedItem());
        int mesec = Integer.parseInt((String) MesecComboBox.getSelectedItem());
        int godina = Integer.parseInt((String) GodinaComboBox.getSelectedItem());
        GregorianCalendar datum = new GregorianCalendar(godina,mesec-1,dan);
        reka.setDatumMerenja(datum);
        
        vodostaj.UnesiReku(reka);
        }
        catch(ExceptionNedozvoljenaVrednost e) {
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_UnesiButtonActionPerformed

    private void PrikaziSveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrikaziSveButtonActionPerformed
        RezultatTextArea.removeAll();
        RezultatTextArea.setText(vodostaj.porukaZaPrikazivanje());
    }//GEN-LAST:event_PrikaziSveButtonActionPerformed

    private void IzvestajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzvestajButtonActionPerformed
        vodostaj.GenerisiIzvestaj();
    }//GEN-LAST:event_IzvestajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vodostajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vodostajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vodostajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vodostajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vodostajForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DanComboBox;
    private javax.swing.JComboBox<String> GodinaComboBox;
    private javax.swing.JButton IzvestajButton;
    private javax.swing.JComboBox<String> MesecComboBox;
    private javax.swing.JTextPane NazivTextPane;
    private javax.swing.JButton PrikaziSveButton;
    private javax.swing.JTextArea RezultatTextArea;
    private javax.swing.JButton UnesiButton;
    private javax.swing.JTextPane VodostajTextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
