/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pravna_lica.prodaja;

import pravna_lica.Preduzece;
import pravna_lica.ExceptionNedozvoljenaVrednost;
import java.io.FileNotFoundException;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jana Jovanovic
 */
public class ProdajaNaVelikoForm extends javax.swing.JFrame {

    /**
     * Creates new form ProdajaNaVelikoForm
     */
    ProdajaNaVelikoGUI prodajaNaVelikoGUI = new ProdajaNaVelikoGUI();
    
    public ProdajaNaVelikoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PIBTextField = new javax.swing.JTextField();
        NazivTextField = new javax.swing.JTextField();
        AdresaTextField = new javax.swing.JTextField();
        TelefonTextField = new javax.swing.JTextField();
        DodajButton = new javax.swing.JButton();
        ObrisiButton = new javax.swing.JButton();
        SacuvajButton = new javax.swing.JButton();
        IznosTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prodaja na veliko");

        jLabel1.setText("PIB");

        jLabel2.setText("Naziv");

        jLabel3.setText("Adresa");

        jLabel4.setText("Iznos");

        jLabel5.setText("Telefon");

        NazivTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazivTextFieldActionPerformed(evt);
            }
        });

        AdresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresaTextFieldActionPerformed(evt);
            }
        });

        TelefonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonTextFieldActionPerformed(evt);
            }
        });

        DodajButton.setText("Dodaj");
        DodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajButtonActionPerformed(evt);
            }
        });

        ObrisiButton.setText("Obrisi");
        ObrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiButtonActionPerformed(evt);
            }
        });

        SacuvajButton.setText("Sacuvaj");
        SacuvajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacuvajButtonActionPerformed(evt);
            }
        });

        IznosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IznosTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IznosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(PIBTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdresaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NazivTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObrisiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SacuvajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PIBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(NazivTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ObrisiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SacuvajButton)
                    .addComponent(AdresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(TelefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IznosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazivTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazivTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NazivTextFieldActionPerformed

    private void AdresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresaTextFieldActionPerformed

    private void TelefonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonTextFieldActionPerformed

    private void IznosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IznosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IznosTextFieldActionPerformed

    private void DodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajButtonActionPerformed
       try{
        Racun racun = new Racun();
        Preduzece preduzece = new Preduzece();
        
        preduzece.setPIB(Integer.parseInt(PIBTextField.getText()));
        preduzece.setNaziv(NazivTextField.getText());
        preduzece.setAdresa(AdresaTextField.getText());
        preduzece.setTelefon(Integer.parseInt(TelefonTextField.getText()));
        racun.setPreduzece(preduzece);
        racun.setIznos(Integer.parseInt(IznosTextField.getText()));
        
        GregorianCalendar today = new GregorianCalendar(TimeZone.getTimeZone("GMT+5:30"));
        racun.setDatum(today);
        
        prodajaNaVelikoGUI.DodajRacun(racun);
        
       } catch (ExceptionNedozvoljenaVrednost e) {
            System.out.println(e.toString());

        }
               
    }//GEN-LAST:event_DodajButtonActionPerformed

    private void ObrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiButtonActionPerformed
        // TODO add your handling code here:
        prodajaNaVelikoGUI.Obrisi(Integer.parseInt(PIBTextField.getText()));
        
        PIBTextField.setText("");
        NazivTextField.setText("");
        AdresaTextField.setText("");
        TelefonTextField.setText("");
        IznosTextField.setText("");
    }//GEN-LAST:event_ObrisiButtonActionPerformed

    private void SacuvajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacuvajButtonActionPerformed

        try {
            prodajaNaVelikoGUI.UpisiUFajl();
        } catch (FileNotFoundException ex) {
        }
        
    }//GEN-LAST:event_SacuvajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdajaNaVelikoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdajaNaVelikoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdajaNaVelikoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdajaNaVelikoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdajaNaVelikoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresaTextField;
    private javax.swing.JButton DodajButton;
    private javax.swing.JTextField IznosTextField;
    private javax.swing.JTextField NazivTextField;
    private javax.swing.JButton ObrisiButton;
    private javax.swing.JTextField PIBTextField;
    private javax.swing.JButton SacuvajButton;
    private javax.swing.JTextField TelefonTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
